# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Jekyll + Gulp
email: dkoch@sagetopia.com
description: Site description asdfasd fas f
baseurl: ''
# baseurl: "/jekyll" # the subpath of your site, e.g. /blog
url: "http://wherebethedan.github.io" # the base hostname & protocol for your site
twitter_username: wherebethedan
github_username:  wherebethedan

# Build settings
markdown: kramdown
include: ['_pages']
exclude: ['package.json', 'node_modules', 'gulpfile.js']

# Posts
permalink: /articles/:year/:month/:title/

# Collections
collections:
  portfolios:
    output: true
    permalink: /portfolio/:path/